server:
  port: 8089 # 保持你原有的端口
  tomcat:
    accesslog:
      enabled: true          # 开启访问日志
      directory: logs        # 日志存放目录 (默认在项目根目录下的 logs 文件夹)
      prefix: access_log     # 文件名前缀
      suffix: .log           # 文件后缀
      pattern: "%h %l %u %t \"%r\" %s %b \"%{User-Agent}i\"" # 自定义格式
      # 解释 pattern:
      # %h = 客户端 IP (这就是你要找的!)
      # %t = 时间
      # %r = 请求行 (包含 URL 和 Method)
      # %s = 状态码
      # %b = 响应大小
      # %{User-Agent}i = 用户代理 (可以看到攻击者的工具特征)

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    # url: jdbc:mysql://22.188.9.144:3306/stack_db?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    url: jdbc:mysql://localhost:3306/stack_db?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    # password: Star002!
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MyBatis Plus 配置
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.bocfintech.allstar.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.bocfintech.allstar: debug
    org.springframework.web.socket: debug
    com.bocfintech.allstar.mapper: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mysql:
  host: 22.188.9.16
  port: 3306
  user-name: td
  password: Mtx0422!
  database: allstar
  charset: utf8mb4

export:
  tables:
    - ai_case
    - ai_component_test_case
    - ai_function
    - parking_book
    - parking_record
    - sys_cal_batch_config
    - sys_cal_code
    - sys_group
    - sys_number
    - sys_roles
    - sys_team
    - work_reminder
    - work_supplement_info
  output-path: "D:/data/mysql-backup/"
  temp-path: "D:/data/temp/"

vote:
  upload-path: "D:/data/aicode-v1/uploads/vote/"

tdsql:
  host: 81.88.153.53
  port: 15252
  user-name: aicoding
  password: AI@aic021!!!
  database: allstar
  charset: utf8mb4

import:
  tables:
    - parking_book
    - parking_record
  input-path: "D:/data/mysql-backup/"
  temp-path: "D:/data/temp/"